# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Adam Waring 
tagline:             'Hobby projects'
description:         'A compilation my academic and just-for-fun data science projects.'
url:                 https://adamwaring.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Adam Waring 
  url:               https://twitter.com/Adam_Waring_
  email:             adamwar@well.ox.ac.uk

# Custom vars
version:             1.0.0
